### ISSUE TITLE
Imports/Suggests

### ISSUE THREAD

**Issue by assignUser** [lorenzwalthert/touchstone#48]
@lorenzwalthert  I just noticed that you list dplyr, withr, glue , ggplot2 ... in suggests only, should they not be listed as imports?  At least dplyr and ggplot2 as we don't have anything else afaik that depends on it compared to glue etc.

**Comment by lorenzwalthert** [comment]
In general, I have been very carefully in adding hard dependencies to reduce build times. Also, it's always easier to add dependencies (because you get an error which ones are missing) compared to removing unnecessary ones. As a bare minimum, I think you need to create benchmarks and read them. That's what I intended to put in Imports. Suggests has dependencies to summarize, visualize and testing.

Note that {ggplot} and {dplyr} are imported in the GitHub Actions Script.

* {digest}: only used in testing.
* {dplyr}: Quite dependency heavy and if no binary available, compiling takes long. It's strictly not required to create benchmarks, or read them, but only summarize and visualize it.
* {glue}: Only used in only summarize and visualize or testing. There is one usage in `run_script()` that actually does not even require glue. We should remove that call there.  E.g. in #49 ⚠️ ?
* {knitr}: used for vignettes, so that's fine in Suggest.
* {rmarkdown} used for vignettes, so that's fine in Suggest.
* {testthat}: only used for testing.
* {withr}: Takes 6s on my old machine to install, mainly used in testing but also in other place, so ok to import it. ✅

**Comment by assignUser** [comment]
I see were you are coming from and agree with {dplyr}, we should the check for its availability thought and error gracefully. {mockery} is only used in testing so should be suggested?

Over all there quite a few "free" imports aka they are imported by other packages we definitely need:
* {fs}, {gert}, {glue}, {purrr}, {rlang}, {withr} are imported by usethis 
    *  We only use usethis for the cli stuff which was refactored into {cli} which only imports {glue}so we could think about replacing that, as {usethis} probably takes longer to install then {cli}? haven't checked though.
* {openssl} is imported by {gert}
* {magrittr} and {rlang} come with {purrr}
* {tidyselect} is only used in analyse -> like {dplyr} in suggests

So I think Imports and Suggests should look like this  (with check for dplyr):

```
Imports: 
    bench,
    callr,
    fs,
    gert,
    glue, (free)
    magrittr, (free)
    purrr,
    remotes, 
    rlang, (free)
    tibble,
    usethis, <- replace with {cli}?
    vctrs,
    withr
Suggests: 
    dplyr, 
    ggplot2,
    knitr,
    mockery (>= 0.4.2),
    openssl (>= 1.4.1), (free)
    rmarkdown,
    tidyselect, (free)
    testthat (>= 3.0.0)
```

**Comment by lorenzwalthert** [comment]
Ok sure. Thanks for the analysis. We can go ahead like this.
