### ISSUE TITLE
Workflow documentation

### ISSUE THREAD

**Issue by lorenzwalthert** [lorenzwalthert/touchstone#79]
@assignUser what do you think of this (detail suggestions also welcome)? I think we could create a vignette and add some paragraph.

![Screenshot 2021-11-20 at 12 18 09](https://user-images.githubusercontent.com/10477073/142724374-e6d6464a-fe51-4020-a734-af3026587df8.png)

As pdf: [workflow-visualization.pdf](https://github.com/lorenzwalthert/touchstone/files/7574444/workflow-visualization.pdf)

**Comment by assignUser** [comment]
Oh nice, I like the idea and overall look! I think it is visually unbalanced with the "manual" side lacking any kind of frame compared to the gha side. Maybe a frame with `R-Terminal` on it or something like that would balance it out?

I think the grey for the yaml file frames and text is a bit to light and due to that to hard to read. A darker grey or the Github-purple (`#6e5494`) (and then an R blue for the terminal frame?) might read better?

And finally you are missing a word here:
 >All that `run_script` **does** except ...

**Comment by lorenzwalthert** [comment]
Thanks for the feedback I will adapt. I’ll also add more on  asset pinning.
